/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface IAdsMetadataArgs {
    ad_break_start_time_ms?: number | Int64;
}
export class AdsMetadata {
    public ad_break_start_time_ms?: Int64;
    constructor(args?: IAdsMetadataArgs) {
        if (args != null && args.ad_break_start_time_ms != null) {
            if (typeof args.ad_break_start_time_ms === "number") {
                this.ad_break_start_time_ms = new Int64(args.ad_break_start_time_ms);
            }
            else {
                this.ad_break_start_time_ms = args.ad_break_start_time_ms;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("AdsMetadata");
        if (this.ad_break_start_time_ms != null) {
            output.writeFieldBegin("ad_break_start_time_ms", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.ad_break_start_time_ms);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): AdsMetadata {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_1: Int64 = input.readI64();
                        _args.ad_break_start_time_ms = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new AdsMetadata(_args);
    }
}
