/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IAudioDuplicationDebugInfoArgs {
    duplicationAmount?: number;
    delayMs?: number;
}
export class AudioDuplicationDebugInfo {
    public duplicationAmount?: number;
    public delayMs?: number;
    constructor(args?: IAudioDuplicationDebugInfoArgs) {
        if (args != null && args.duplicationAmount != null) {
            this.duplicationAmount = args.duplicationAmount;
        }
        if (args != null && args.delayMs != null) {
            this.delayMs = args.delayMs;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("AudioDuplicationDebugInfo");
        if (this.duplicationAmount != null) {
            output.writeFieldBegin("duplicationAmount", thrift.Thrift.Type.I16, 1);
            output.writeI16(this.duplicationAmount);
            output.writeFieldEnd();
        }
        if (this.delayMs != null) {
            output.writeFieldBegin("delayMs", thrift.Thrift.Type.I16, 2);
            output.writeI16(this.delayMs);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): AudioDuplicationDebugInfo {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I16) {
                        const value_1: number = input.readI16();
                        _args.duplicationAmount = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I16) {
                        const value_2: number = input.readI16();
                        _args.delayMs = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new AudioDuplicationDebugInfo(_args);
    }
}
