/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IAudioAttributionArgs {
    artist_name?: string;
    song_title?: string;
}
export class AudioAttribution {
    public artist_name?: string;
    public song_title?: string;
    constructor(args?: IAudioAttributionArgs) {
        if (args != null && args.artist_name != null) {
            this.artist_name = args.artist_name;
        }
        if (args != null && args.song_title != null) {
            this.song_title = args.song_title;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("AudioAttribution");
        if (this.artist_name != null) {
            output.writeFieldBegin("artist_name", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.artist_name);
            output.writeFieldEnd();
        }
        if (this.song_title != null) {
            output.writeFieldBegin("song_title", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.song_title);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): AudioAttribution {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.artist_name = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.song_title = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new AudioAttribution(_args);
    }
}
