/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
import * as Content from "./Content";
export interface IAutoplayOutputArgs {
    action_id?: string;
    content_source?: number;
    content_id?: string;
    content?: Content.Content;
    display_state?: number;
    preview_duration_ms?: number | Int64;
}
export class AutoplayOutput {
    public action_id?: string;
    public content_source?: number;
    public content_id?: string;
    public content?: Content.Content;
    public display_state?: number;
    public preview_duration_ms?: Int64;
    constructor(args?: IAutoplayOutputArgs) {
        if (args != null && args.action_id != null) {
            this.action_id = args.action_id;
        }
        if (args != null && args.content_source != null) {
            this.content_source = args.content_source;
        }
        if (args != null && args.content_id != null) {
            this.content_id = args.content_id;
        }
        if (args != null && args.content != null) {
            this.content = args.content;
        }
        if (args != null && args.display_state != null) {
            this.display_state = args.display_state;
        }
        if (args != null && args.preview_duration_ms != null) {
            if (typeof args.preview_duration_ms === "number") {
                this.preview_duration_ms = new Int64(args.preview_duration_ms);
            }
            else {
                this.preview_duration_ms = args.preview_duration_ms;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("AutoplayOutput");
        if (this.action_id != null) {
            output.writeFieldBegin("action_id", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.action_id);
            output.writeFieldEnd();
        }
        if (this.content_source != null) {
            output.writeFieldBegin("content_source", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.content_source);
            output.writeFieldEnd();
        }
        if (this.content_id != null) {
            output.writeFieldBegin("content_id", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.content_id);
            output.writeFieldEnd();
        }
        if (this.content != null) {
            output.writeFieldBegin("content", thrift.Thrift.Type.STRUCT, 4);
            this.content.write(output);
            output.writeFieldEnd();
        }
        if (this.display_state != null) {
            output.writeFieldBegin("display_state", thrift.Thrift.Type.I32, 5);
            output.writeI32(this.display_state);
            output.writeFieldEnd();
        }
        if (this.preview_duration_ms != null) {
            output.writeFieldBegin("preview_duration_ms", thrift.Thrift.Type.I64, 6);
            output.writeI64(this.preview_duration_ms);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): AutoplayOutput {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.action_id = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.content_source = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.content_id = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_4: Content.Content = Content.Content.read(input);
                        _args.content = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_5: number = input.readI32();
                        _args.display_state = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_6: Int64 = input.readI64();
                        _args.preview_duration_ms = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new AutoplayOutput(_args);
    }
}
