/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IBandwidthArgs {
    bwtype?: string;
    bw?: number;
}
export class Bandwidth {
    public bwtype?: string;
    public bw?: number;
    constructor(args?: IBandwidthArgs) {
        if (args != null && args.bwtype != null) {
            this.bwtype = args.bwtype;
        }
        if (args != null && args.bw != null) {
            this.bw = args.bw;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("Bandwidth");
        if (this.bwtype != null) {
            output.writeFieldBegin("bwtype", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.bwtype);
            output.writeFieldEnd();
        }
        if (this.bw != null) {
            output.writeFieldBegin("bw", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.bw);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): Bandwidth {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.bwtype = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.bw = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new Bandwidth(_args);
    }
}
