/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ICathodeExtensionParticipantInputStateArgs {
    useCase?: number;
    useCaseParticipantInputState?: string;
}
export class CathodeExtensionParticipantInputState {
    public useCase?: number;
    public useCaseParticipantInputState?: string;
    constructor(args?: ICathodeExtensionParticipantInputStateArgs) {
        if (args != null && args.useCase != null) {
            this.useCase = args.useCase;
        }
        if (args != null && args.useCaseParticipantInputState != null) {
            this.useCaseParticipantInputState = args.useCaseParticipantInputState;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("CathodeExtensionParticipantInputState");
        if (this.useCase != null) {
            output.writeFieldBegin("useCase", thrift.Thrift.Type.I32, 1);
            output.writeI32(this.useCase);
            output.writeFieldEnd();
        }
        if (this.useCaseParticipantInputState != null) {
            output.writeFieldBegin("useCaseParticipantInputState", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.useCaseParticipantInputState);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): CathodeExtensionParticipantInputState {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_1: number = input.readI32();
                        _args.useCase = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.useCaseParticipantInputState = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new CathodeExtensionParticipantInputState(_args);
    }
}
