/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface ICoplayConferenceInputStateArgs {
    matchId?: number | Int64;
    event?: number;
}
export class CoplayConferenceInputState {
    public matchId?: Int64;
    public event?: number;
    constructor(args?: ICoplayConferenceInputStateArgs) {
        if (args != null && args.matchId != null) {
            if (typeof args.matchId === "number") {
                this.matchId = new Int64(args.matchId);
            }
            else {
                this.matchId = args.matchId;
            }
        }
        if (args != null && args.event != null) {
            this.event = args.event;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("CoplayConferenceInputState");
        if (this.matchId != null) {
            output.writeFieldBegin("matchId", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.matchId);
            output.writeFieldEnd();
        }
        if (this.event != null) {
            output.writeFieldBegin("event", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.event);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): CoplayConferenceInputState {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_1: Int64 = input.readI64();
                        _args.matchId = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.event = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new CoplayConferenceInputState(_args);
    }
}
