/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IDeviceHardwareInfoArgs {
    numCores?: number;
    RAM?: number;
}
export class DeviceHardwareInfo {
    public numCores?: number;
    public RAM?: number;
    constructor(args?: IDeviceHardwareInfoArgs) {
        if (args != null && args.numCores != null) {
            this.numCores = args.numCores;
        }
        if (args != null && args.RAM != null) {
            this.RAM = args.RAM;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("DeviceHardwareInfo");
        if (this.numCores != null) {
            output.writeFieldBegin("numCores", thrift.Thrift.Type.I32, 1);
            output.writeI32(this.numCores);
            output.writeFieldEnd();
        }
        if (this.RAM != null) {
            output.writeFieldBegin("RAM", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.RAM);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): DeviceHardwareInfo {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_1: number = input.readI32();
                        _args.numCores = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.RAM = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new DeviceHardwareInfo(_args);
    }
}
