/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as UserMediaSourceId from "./UserMediaSourceId";
export interface IDominantLayoutExtraArgs {
    dominantUsers?: Array<UserMediaSourceId.UserMediaSourceId>;
}
export class DominantLayoutExtra {
    public dominantUsers?: Array<UserMediaSourceId.UserMediaSourceId>;
    constructor(args?: IDominantLayoutExtraArgs) {
        if (args != null && args.dominantUsers != null) {
            this.dominantUsers = args.dominantUsers;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("DominantLayoutExtra");
        if (this.dominantUsers != null) {
            output.writeFieldBegin("dominantUsers", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.dominantUsers.length);
            this.dominantUsers.forEach((value_1: UserMediaSourceId.UserMediaSourceId): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): DominantLayoutExtra {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_2: Array<UserMediaSourceId.UserMediaSourceId> = new Array<UserMediaSourceId.UserMediaSourceId>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_3: UserMediaSourceId.UserMediaSourceId = UserMediaSourceId.UserMediaSourceId.read(input);
                            value_2.push(value_3);
                        }
                        input.readListEnd();
                        _args.dominantUsers = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new DominantLayoutExtra(_args);
    }
}
