/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IE2EEPMVAdBumperCountArgs {
    last_content_id?: string;
    last_content_source?: number;
    count?: number;
}
export class E2EEPMVAdBumperCount {
    public last_content_id?: string;
    public last_content_source?: number;
    public count?: number;
    constructor(args?: IE2EEPMVAdBumperCountArgs) {
        if (args != null && args.last_content_id != null) {
            this.last_content_id = args.last_content_id;
        }
        if (args != null && args.last_content_source != null) {
            this.last_content_source = args.last_content_source;
        }
        if (args != null && args.count != null) {
            this.count = args.count;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("E2EEPMVAdBumperCount");
        if (this.last_content_id != null) {
            output.writeFieldBegin("last_content_id", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.last_content_id);
            output.writeFieldEnd();
        }
        if (this.last_content_source != null) {
            output.writeFieldBegin("last_content_source", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.last_content_source);
            output.writeFieldEnd();
        }
        if (this.count != null) {
            output.writeFieldBegin("count", thrift.Thrift.Type.I32, 3);
            output.writeI32(this.count);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): E2EEPMVAdBumperCount {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.last_content_id = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.last_content_source = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_3: number = input.readI32();
                        _args.count = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new E2EEPMVAdBumperCount(_args);
    }
}
