/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IEmojiArgs {
    emoji_id?: string;
    emoji_click_id?: string;
    reaction_type?: number;
}
export class Emoji {
    public emoji_id?: string;
    public emoji_click_id?: string;
    public reaction_type?: number;
    constructor(args?: IEmojiArgs) {
        if (args != null && args.emoji_id != null) {
            this.emoji_id = args.emoji_id;
        }
        if (args != null && args.emoji_click_id != null) {
            this.emoji_click_id = args.emoji_click_id;
        }
        if (args != null && args.reaction_type != null) {
            this.reaction_type = args.reaction_type;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("Emoji");
        if (this.emoji_id != null) {
            output.writeFieldBegin("emoji_id", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.emoji_id);
            output.writeFieldEnd();
        }
        if (this.emoji_click_id != null) {
            output.writeFieldBegin("emoji_click_id", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.emoji_click_id);
            output.writeFieldEnd();
        }
        if (this.reaction_type != null) {
            output.writeFieldBegin("reaction_type", thrift.Thrift.Type.I32, 3);
            output.writeI32(this.reaction_type);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): Emoji {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.emoji_id = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.emoji_click_id = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_3: number = input.readI32();
                        _args.reaction_type = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new Emoji(_args);
    }
}
