/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as ParticipantOutputState from "./ParticipantOutputState";
import * as ConferenceOutputState from "./ConferenceOutputState";
export interface IModeratorControlsOutputStateArgs {
    participant?: ParticipantOutputState.ParticipantOutputState;
    conference?: ConferenceOutputState.ConferenceOutputState;
}
export class ModeratorControlsOutputState {
    public participant?: ParticipantOutputState.ParticipantOutputState;
    public conference?: ConferenceOutputState.ConferenceOutputState;
    constructor(args?: IModeratorControlsOutputStateArgs) {
        if (args != null && args.participant != null) {
            this.participant = args.participant;
        }
        if (args != null && args.conference != null) {
            this.conference = args.conference;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ModeratorControlsOutputState");
        if (this.participant != null) {
            output.writeFieldBegin("participant", thrift.Thrift.Type.STRUCT, 1);
            this.participant.write(output);
            output.writeFieldEnd();
        }
        if (this.conference != null) {
            output.writeFieldBegin("conference", thrift.Thrift.Type.STRUCT, 2);
            this.conference.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ModeratorControlsOutputState {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_1: ParticipantOutputState.ParticipantOutputState = ParticipantOutputState.ParticipantOutputState.read(input);
                        _args.participant = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_2: ConferenceOutputState.ConferenceOutputState = ConferenceOutputState.ConferenceOutputState.read(input);
                        _args.conference = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ModeratorControlsOutputState(_args);
    }
}
