/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IModeratorInputStateArgs {
    allows_screen_share?: boolean;
    issue_action?: number;
    issue_action_target_uids?: Set<string>;
    issue_action_context_serialized?: string;
}
export class ModeratorInputState {
    public allows_screen_share?: boolean;
    public issue_action?: number;
    public issue_action_target_uids?: Set<string>;
    public issue_action_context_serialized?: string;
    constructor(args?: IModeratorInputStateArgs) {
        if (args != null && args.allows_screen_share != null) {
            this.allows_screen_share = args.allows_screen_share;
        }
        if (args != null && args.issue_action != null) {
            this.issue_action = args.issue_action;
        }
        if (args != null && args.issue_action_target_uids != null) {
            this.issue_action_target_uids = args.issue_action_target_uids;
        }
        if (args != null && args.issue_action_context_serialized != null) {
            this.issue_action_context_serialized = args.issue_action_context_serialized;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ModeratorInputState");
        if (this.allows_screen_share != null) {
            output.writeFieldBegin("allows_screen_share", thrift.Thrift.Type.BOOL, 1);
            output.writeBool(this.allows_screen_share);
            output.writeFieldEnd();
        }
        if (this.issue_action != null) {
            output.writeFieldBegin("issue_action", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.issue_action);
            output.writeFieldEnd();
        }
        if (this.issue_action_target_uids != null) {
            output.writeFieldBegin("issue_action_target_uids", thrift.Thrift.Type.SET, 3);
            output.writeSetBegin(thrift.Thrift.Type.STRING, this.issue_action_target_uids.size);
            this.issue_action_target_uids.forEach((value_1: string): void => {
                output.writeString(value_1);
            });
            output.writeSetEnd();
            output.writeFieldEnd();
        }
        if (this.issue_action_context_serialized != null) {
            output.writeFieldBegin("issue_action_context_serialized", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.issue_action_context_serialized);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ModeratorInputState {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_2: boolean = input.readBool();
                        _args.allows_screen_share = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_3: number = input.readI32();
                        _args.issue_action = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.SET) {
                        const value_4: Set<string> = new Set<string>();
                        const metadata_1: thrift.TSet = input.readSetBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_5: string = input.readString();
                            value_4.add(value_5);
                        }
                        input.readSetEnd();
                        _args.issue_action_target_uids = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_6: string = input.readString();
                        _args.issue_action_context_serialized = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ModeratorInputState(_args);
    }
}
