/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as ParticipantInputState from "./ParticipantInputState";
import * as ModeratorInputState from "./ModeratorInputState";
export interface IModeratorControlsInputStateArgs {
    participant?: ParticipantInputState.ParticipantInputState;
    moderator?: ModeratorInputState.ModeratorInputState;
}
export class ModeratorControlsInputState {
    public participant?: ParticipantInputState.ParticipantInputState;
    public moderator?: ModeratorInputState.ModeratorInputState;
    constructor(args?: IModeratorControlsInputStateArgs) {
        if (args != null && args.participant != null) {
            this.participant = args.participant;
        }
        if (args != null && args.moderator != null) {
            this.moderator = args.moderator;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ModeratorControlsInputState");
        if (this.participant != null) {
            output.writeFieldBegin("participant", thrift.Thrift.Type.STRUCT, 1);
            this.participant.write(output);
            output.writeFieldEnd();
        }
        if (this.moderator != null) {
            output.writeFieldBegin("moderator", thrift.Thrift.Type.STRUCT, 2);
            this.moderator.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ModeratorControlsInputState {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_1: ParticipantInputState.ParticipantInputState = ParticipantInputState.ParticipantInputState.read(input);
                        _args.participant = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_2: ModeratorInputState.ModeratorInputState = ModeratorInputState.ModeratorInputState.read(input);
                        _args.moderator = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ModeratorControlsInputState(_args);
    }
}
