/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface INumberOfPeopleInputStateArgs {
    number_of_people?: number;
}
export class NumberOfPeopleInputState {
    public number_of_people?: number;
    constructor(args?: INumberOfPeopleInputStateArgs) {
        if (args != null && args.number_of_people != null) {
            this.number_of_people = args.number_of_people;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("NumberOfPeopleInputState");
        if (this.number_of_people != null) {
            output.writeFieldBegin("number_of_people", thrift.Thrift.Type.I32, 1);
            output.writeI32(this.number_of_people);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): NumberOfPeopleInputState {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_1: number = input.readI32();
                        _args.number_of_people = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new NumberOfPeopleInputState(_args);
    }
}
