/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IPollOptionPermissionsArgs {
    can_vote?: boolean;
    can_remove_vote?: boolean;
}
export class PollOptionPermissions {
    public can_vote?: boolean;
    public can_remove_vote?: boolean;
    constructor(args?: IPollOptionPermissionsArgs) {
        if (args != null && args.can_vote != null) {
            this.can_vote = args.can_vote;
        }
        if (args != null && args.can_remove_vote != null) {
            this.can_remove_vote = args.can_remove_vote;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("PollOptionPermissions");
        if (this.can_vote != null) {
            output.writeFieldBegin("can_vote", thrift.Thrift.Type.BOOL, 1);
            output.writeBool(this.can_vote);
            output.writeFieldEnd();
        }
        if (this.can_remove_vote != null) {
            output.writeFieldBegin("can_remove_vote", thrift.Thrift.Type.BOOL, 2);
            output.writeBool(this.can_remove_vote);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): PollOptionPermissions {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_1: boolean = input.readBool();
                        _args.can_vote = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_2: boolean = input.readBool();
                        _args.can_remove_vote = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new PollOptionPermissions(_args);
    }
}
