/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as ProxygenAllocation from "./ProxygenAllocation";
export interface IProxygenAllocationResultArgs {
    allocations?: Array<ProxygenAllocation.ProxygenAllocation>;
    proxygenVipType?: number;
    vipTypeAllocationsMap?: Map<number, Array<ProxygenAllocation.ProxygenAllocation>>;
}
export class ProxygenAllocationResult {
    public allocations?: Array<ProxygenAllocation.ProxygenAllocation>;
    public proxygenVipType?: number;
    public vipTypeAllocationsMap?: Map<number, Array<ProxygenAllocation.ProxygenAllocation>>;
    constructor(args?: IProxygenAllocationResultArgs) {
        if (args != null && args.allocations != null) {
            this.allocations = args.allocations;
        }
        if (args != null && args.proxygenVipType != null) {
            this.proxygenVipType = args.proxygenVipType;
        }
        if (args != null && args.vipTypeAllocationsMap != null) {
            this.vipTypeAllocationsMap = args.vipTypeAllocationsMap;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ProxygenAllocationResult");
        if (this.allocations != null) {
            output.writeFieldBegin("allocations", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.allocations.length);
            this.allocations.forEach((value_1: ProxygenAllocation.ProxygenAllocation): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.proxygenVipType != null) {
            output.writeFieldBegin("proxygenVipType", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.proxygenVipType);
            output.writeFieldEnd();
        }
        if (this.vipTypeAllocationsMap != null) {
            output.writeFieldBegin("vipTypeAllocationsMap", thrift.Thrift.Type.MAP, 3);
            output.writeMapBegin(thrift.Thrift.Type.I32, thrift.Thrift.Type.LIST, this.vipTypeAllocationsMap.size);
            this.vipTypeAllocationsMap.forEach((value_2: Array<ProxygenAllocation.ProxygenAllocation>, key_1: number): void => {
                output.writeI32(key_1);
                output.writeListBegin(thrift.Thrift.Type.STRUCT, value_2.length);
                value_2.forEach((value_3: ProxygenAllocation.ProxygenAllocation): void => {
                    value_3.write(output);
                });
                output.writeListEnd();
            });
            output.writeMapEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ProxygenAllocationResult {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_4: Array<ProxygenAllocation.ProxygenAllocation> = new Array<ProxygenAllocation.ProxygenAllocation>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_5: ProxygenAllocation.ProxygenAllocation = ProxygenAllocation.ProxygenAllocation.read(input);
                            value_4.push(value_5);
                        }
                        input.readListEnd();
                        _args.allocations = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_6: number = input.readI32();
                        _args.proxygenVipType = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.MAP) {
                        const value_7: Map<number, Array<ProxygenAllocation.ProxygenAllocation>> = new Map<number, Array<ProxygenAllocation.ProxygenAllocation>>();
                        const metadata_2: thrift.TMap = input.readMapBegin();
                        const size_2: number = metadata_2.size;
                        for (let i_2: number = 0; i_2 < size_2; i_2++) {
                            const key_2: number = input.readI32();
                            const value_8: Array<ProxygenAllocation.ProxygenAllocation> = new Array<ProxygenAllocation.ProxygenAllocation>();
                            const metadata_3: thrift.TList = input.readListBegin();
                            const size_3: number = metadata_3.size;
                            for (let i_3: number = 0; i_3 < size_3; i_3++) {
                                const value_9: ProxygenAllocation.ProxygenAllocation = ProxygenAllocation.ProxygenAllocation.read(input);
                                value_8.push(value_9);
                            }
                            input.readListEnd();
                            value_7.set(key_2, value_8);
                        }
                        input.readMapEnd();
                        _args.vipTypeAllocationsMap = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ProxygenAllocationResult(_args);
    }
}
