/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as RaisedHandsQueuer from "./RaisedHandsQueuer";
export interface IRaisedHandsQueueConferenceOutputStateArgs {
    queue?: Array<RaisedHandsQueuer.RaisedHandsQueuer>;
    is_raise_hand_feature_enabled?: boolean;
    moderator_uids_if_empty_means_everyone_is_moderator?: Set<string>;
    call_type?: number;
    participant_id_to_processed_action_uuids?: Map<string, Set<string>>;
    use_rtss?: boolean;
}
export class RaisedHandsQueueConferenceOutputState {
    public queue?: Array<RaisedHandsQueuer.RaisedHandsQueuer>;
    public is_raise_hand_feature_enabled?: boolean;
    public moderator_uids_if_empty_means_everyone_is_moderator?: Set<string>;
    public call_type?: number;
    public participant_id_to_processed_action_uuids?: Map<string, Set<string>>;
    public use_rtss?: boolean;
    constructor(args?: IRaisedHandsQueueConferenceOutputStateArgs) {
        if (args != null && args.queue != null) {
            this.queue = args.queue;
        }
        if (args != null && args.is_raise_hand_feature_enabled != null) {
            this.is_raise_hand_feature_enabled = args.is_raise_hand_feature_enabled;
        }
        if (args != null && args.moderator_uids_if_empty_means_everyone_is_moderator != null) {
            this.moderator_uids_if_empty_means_everyone_is_moderator = args.moderator_uids_if_empty_means_everyone_is_moderator;
        }
        if (args != null && args.call_type != null) {
            this.call_type = args.call_type;
        }
        if (args != null && args.participant_id_to_processed_action_uuids != null) {
            this.participant_id_to_processed_action_uuids = args.participant_id_to_processed_action_uuids;
        }
        if (args != null && args.use_rtss != null) {
            this.use_rtss = args.use_rtss;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("RaisedHandsQueueConferenceOutputState");
        if (this.queue != null) {
            output.writeFieldBegin("queue", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.queue.length);
            this.queue.forEach((value_1: RaisedHandsQueuer.RaisedHandsQueuer): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.is_raise_hand_feature_enabled != null) {
            output.writeFieldBegin("is_raise_hand_feature_enabled", thrift.Thrift.Type.BOOL, 2);
            output.writeBool(this.is_raise_hand_feature_enabled);
            output.writeFieldEnd();
        }
        if (this.moderator_uids_if_empty_means_everyone_is_moderator != null) {
            output.writeFieldBegin("moderator_uids_if_empty_means_everyone_is_moderator", thrift.Thrift.Type.SET, 4);
            output.writeSetBegin(thrift.Thrift.Type.STRING, this.moderator_uids_if_empty_means_everyone_is_moderator.size);
            this.moderator_uids_if_empty_means_everyone_is_moderator.forEach((value_2: string): void => {
                output.writeString(value_2);
            });
            output.writeSetEnd();
            output.writeFieldEnd();
        }
        if (this.call_type != null) {
            output.writeFieldBegin("call_type", thrift.Thrift.Type.I32, 5);
            output.writeI32(this.call_type);
            output.writeFieldEnd();
        }
        if (this.participant_id_to_processed_action_uuids != null) {
            output.writeFieldBegin("participant_id_to_processed_action_uuids", thrift.Thrift.Type.MAP, 6);
            output.writeMapBegin(thrift.Thrift.Type.STRING, thrift.Thrift.Type.SET, this.participant_id_to_processed_action_uuids.size);
            this.participant_id_to_processed_action_uuids.forEach((value_3: Set<string>, key_1: string): void => {
                output.writeString(key_1);
                output.writeSetBegin(thrift.Thrift.Type.STRING, value_3.size);
                value_3.forEach((value_4: string): void => {
                    output.writeString(value_4);
                });
                output.writeSetEnd();
            });
            output.writeMapEnd();
            output.writeFieldEnd();
        }
        if (this.use_rtss != null) {
            output.writeFieldBegin("use_rtss", thrift.Thrift.Type.BOOL, 7);
            output.writeBool(this.use_rtss);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): RaisedHandsQueueConferenceOutputState {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_5: Array<RaisedHandsQueuer.RaisedHandsQueuer> = new Array<RaisedHandsQueuer.RaisedHandsQueuer>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_6: RaisedHandsQueuer.RaisedHandsQueuer = RaisedHandsQueuer.RaisedHandsQueuer.read(input);
                            value_5.push(value_6);
                        }
                        input.readListEnd();
                        _args.queue = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_7: boolean = input.readBool();
                        _args.is_raise_hand_feature_enabled = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.SET) {
                        const value_8: Set<string> = new Set<string>();
                        const metadata_2: thrift.TSet = input.readSetBegin();
                        const size_2: number = metadata_2.size;
                        for (let i_2: number = 0; i_2 < size_2; i_2++) {
                            const value_9: string = input.readString();
                            value_8.add(value_9);
                        }
                        input.readSetEnd();
                        _args.moderator_uids_if_empty_means_everyone_is_moderator = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_10: number = input.readI32();
                        _args.call_type = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.MAP) {
                        const value_11: Map<string, Set<string>> = new Map<string, Set<string>>();
                        const metadata_3: thrift.TMap = input.readMapBegin();
                        const size_3: number = metadata_3.size;
                        for (let i_3: number = 0; i_3 < size_3; i_3++) {
                            const key_2: string = input.readString();
                            const value_12: Set<string> = new Set<string>();
                            const metadata_4: thrift.TSet = input.readSetBegin();
                            const size_4: number = metadata_4.size;
                            for (let i_4: number = 0; i_4 < size_4; i_4++) {
                                const value_13: string = input.readString();
                                value_12.add(value_13);
                            }
                            input.readSetEnd();
                            value_11.set(key_2, value_12);
                        }
                        input.readMapEnd();
                        _args.participant_id_to_processed_action_uuids = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_14: boolean = input.readBool();
                        _args.use_rtss = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new RaisedHandsQueueConferenceOutputState(_args);
    }
}
