/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IResolutionDataArgs {
    userId?: string;
    streamId?: string;
    streamType?: number;
    renderWidth?: number;
    renderHeight?: number;
}
export class ResolutionData {
    public userId?: string;
    public streamId?: string;
    public streamType?: number;
    public renderWidth?: number;
    public renderHeight?: number;
    constructor(args?: IResolutionDataArgs) {
        if (args != null && args.userId != null) {
            this.userId = args.userId;
        }
        if (args != null && args.streamId != null) {
            this.streamId = args.streamId;
        }
        if (args != null && args.streamType != null) {
            this.streamType = args.streamType;
        }
        if (args != null && args.renderWidth != null) {
            this.renderWidth = args.renderWidth;
        }
        if (args != null && args.renderHeight != null) {
            this.renderHeight = args.renderHeight;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ResolutionData");
        if (this.userId != null) {
            output.writeFieldBegin("userId", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.userId);
            output.writeFieldEnd();
        }
        if (this.streamId != null) {
            output.writeFieldBegin("streamId", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.streamId);
            output.writeFieldEnd();
        }
        if (this.streamType != null) {
            output.writeFieldBegin("streamType", thrift.Thrift.Type.I32, 3);
            output.writeI32(this.streamType);
            output.writeFieldEnd();
        }
        if (this.renderWidth != null) {
            output.writeFieldBegin("renderWidth", thrift.Thrift.Type.I32, 4);
            output.writeI32(this.renderWidth);
            output.writeFieldEnd();
        }
        if (this.renderHeight != null) {
            output.writeFieldBegin("renderHeight", thrift.Thrift.Type.I32, 5);
            output.writeI32(this.renderHeight);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ResolutionData {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.userId = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.streamId = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_3: number = input.readI32();
                        _args.streamType = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_4: number = input.readI32();
                        _args.renderWidth = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_5: number = input.readI32();
                        _args.renderHeight = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ResolutionData(_args);
    }
}
