/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IRingResponseArgs {
    deviceStatus?: number;
}
export class RingResponse {
    public deviceStatus?: number;
    constructor(args?: IRingResponseArgs) {
        if (args != null && args.deviceStatus != null) {
            this.deviceStatus = args.deviceStatus;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("RingResponse");
        if (this.deviceStatus != null) {
            output.writeFieldBegin("deviceStatus", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.deviceStatus);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): RingResponse {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_1: number = input.readI32();
                        _args.deviceStatus = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new RingResponse(_args);
    }
}
