/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
import * as Sdp from "./Sdp";
import * as StreamInfo from "./StreamInfo";
import * as TrackInfo from "./TrackInfo";
export interface ISdpUpdatePayloadArgs {
    sdpThrift?: Sdp.Sdp;
    ackMessageId?: number | Int64;
    sdpString?: string;
    streamInfos_DEPRECATED?: Map<string, StreamInfo.StreamInfo>;
    trackInfos?: Map<string, TrackInfo.TrackInfo>;
}
export class SdpUpdatePayload {
    public sdpThrift?: Sdp.Sdp;
    public ackMessageId?: Int64;
    public sdpString?: string;
    public streamInfos_DEPRECATED?: Map<string, StreamInfo.StreamInfo>;
    public trackInfos?: Map<string, TrackInfo.TrackInfo>;
    constructor(args?: ISdpUpdatePayloadArgs) {
        if (args != null && args.sdpThrift != null) {
            this.sdpThrift = args.sdpThrift;
        }
        if (args != null && args.ackMessageId != null) {
            if (typeof args.ackMessageId === "number") {
                this.ackMessageId = new Int64(args.ackMessageId);
            }
            else {
                this.ackMessageId = args.ackMessageId;
            }
        }
        if (args != null && args.sdpString != null) {
            this.sdpString = args.sdpString;
        }
        if (args != null && args.streamInfos_DEPRECATED != null) {
            this.streamInfos_DEPRECATED = args.streamInfos_DEPRECATED;
        }
        if (args != null && args.trackInfos != null) {
            this.trackInfos = args.trackInfos;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("SdpUpdatePayload");
        if (this.sdpThrift != null) {
            output.writeFieldBegin("sdpThrift", thrift.Thrift.Type.STRUCT, 1);
            this.sdpThrift.write(output);
            output.writeFieldEnd();
        }
        if (this.ackMessageId != null) {
            output.writeFieldBegin("ackMessageId", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.ackMessageId);
            output.writeFieldEnd();
        }
        if (this.sdpString != null) {
            output.writeFieldBegin("sdpString", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.sdpString);
            output.writeFieldEnd();
        }
        if (this.streamInfos_DEPRECATED != null) {
            output.writeFieldBegin("streamInfos_DEPRECATED", thrift.Thrift.Type.MAP, 4);
            output.writeMapBegin(thrift.Thrift.Type.STRING, thrift.Thrift.Type.STRUCT, this.streamInfos_DEPRECATED.size);
            this.streamInfos_DEPRECATED.forEach((value_1: StreamInfo.StreamInfo, key_1: string): void => {
                output.writeString(key_1);
                value_1.write(output);
            });
            output.writeMapEnd();
            output.writeFieldEnd();
        }
        if (this.trackInfos != null) {
            output.writeFieldBegin("trackInfos", thrift.Thrift.Type.MAP, 5);
            output.writeMapBegin(thrift.Thrift.Type.STRING, thrift.Thrift.Type.STRUCT, this.trackInfos.size);
            this.trackInfos.forEach((value_2: TrackInfo.TrackInfo, key_2: string): void => {
                output.writeString(key_2);
                value_2.write(output);
            });
            output.writeMapEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): SdpUpdatePayload {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_3: Sdp.Sdp = Sdp.Sdp.read(input);
                        _args.sdpThrift = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_4: Int64 = input.readI64();
                        _args.ackMessageId = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_5: string = input.readString();
                        _args.sdpString = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.MAP) {
                        const value_6: Map<string, StreamInfo.StreamInfo> = new Map<string, StreamInfo.StreamInfo>();
                        const metadata_1: thrift.TMap = input.readMapBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const key_3: string = input.readString();
                            const value_7: StreamInfo.StreamInfo = StreamInfo.StreamInfo.read(input);
                            value_6.set(key_3, value_7);
                        }
                        input.readMapEnd();
                        _args.streamInfos_DEPRECATED = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.MAP) {
                        const value_8: Map<string, TrackInfo.TrackInfo> = new Map<string, TrackInfo.TrackInfo>();
                        const metadata_2: thrift.TMap = input.readMapBegin();
                        const size_2: number = metadata_2.size;
                        for (let i_2: number = 0; i_2 < size_2; i_2++) {
                            const key_4: string = input.readString();
                            const value_9: TrackInfo.TrackInfo = TrackInfo.TrackInfo.read(input);
                            value_8.set(key_4, value_9);
                        }
                        input.readMapEnd();
                        _args.trackInfos = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new SdpUpdatePayload(_args);
    }
}
