/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface IServerCaptionsParticipantOutputStateArgs {
    enabled?: boolean;
    dataChannelNodeId?: number | Int64;
}
export class ServerCaptionsParticipantOutputState {
    public enabled?: boolean;
    public dataChannelNodeId?: Int64;
    constructor(args?: IServerCaptionsParticipantOutputStateArgs) {
        if (args != null && args.enabled != null) {
            this.enabled = args.enabled;
        }
        if (args != null && args.dataChannelNodeId != null) {
            if (typeof args.dataChannelNodeId === "number") {
                this.dataChannelNodeId = new Int64(args.dataChannelNodeId);
            }
            else {
                this.dataChannelNodeId = args.dataChannelNodeId;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ServerCaptionsParticipantOutputState");
        if (this.enabled != null) {
            output.writeFieldBegin("enabled", thrift.Thrift.Type.BOOL, 1);
            output.writeBool(this.enabled);
            output.writeFieldEnd();
        }
        if (this.dataChannelNodeId != null) {
            output.writeFieldBegin("dataChannelNodeId", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.dataChannelNodeId);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ServerCaptionsParticipantOutputState {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_1: boolean = input.readBool();
                        _args.enabled = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.dataChannelNodeId = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ServerCaptionsParticipantOutputState(_args);
    }
}
