/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IShoppingProductTagArgs {
    product_id?: string;
    product_name?: string;
    product_position_x?: string;
    product_position_y?: string;
}
export class ShoppingProductTag {
    public product_id?: string;
    public product_name?: string;
    public product_position_x?: string;
    public product_position_y?: string;
    constructor(args?: IShoppingProductTagArgs) {
        if (args != null && args.product_id != null) {
            this.product_id = args.product_id;
        }
        if (args != null && args.product_name != null) {
            this.product_name = args.product_name;
        }
        if (args != null && args.product_position_x != null) {
            this.product_position_x = args.product_position_x;
        }
        if (args != null && args.product_position_y != null) {
            this.product_position_y = args.product_position_y;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ShoppingProductTag");
        if (this.product_id != null) {
            output.writeFieldBegin("product_id", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.product_id);
            output.writeFieldEnd();
        }
        if (this.product_name != null) {
            output.writeFieldBegin("product_name", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.product_name);
            output.writeFieldEnd();
        }
        if (this.product_position_x != null) {
            output.writeFieldBegin("product_position_x", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.product_position_x);
            output.writeFieldEnd();
        }
        if (this.product_position_y != null) {
            output.writeFieldBegin("product_position_y", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.product_position_y);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ShoppingProductTag {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.product_id = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.product_name = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.product_position_x = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.product_position_y = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ShoppingProductTag(_args);
    }
}
