/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ISimpleOutputStateArgs {
    max?: number;
}
export class SimpleOutputState {
    public max?: number;
    constructor(args?: ISimpleOutputStateArgs) {
        if (args != null && args.max != null) {
            this.max = args.max;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("SimpleOutputState");
        if (this.max != null) {
            output.writeFieldBegin("max", thrift.Thrift.Type.I32, 1);
            output.writeI32(this.max);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): SimpleOutputState {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_1: number = input.readI32();
                        _args.max = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new SimpleOutputState(_args);
    }
}
