/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ISubscriptionOptionsArgs {
    videoQuality?: number;
    qualityIndex?: number;
}
export class SubscriptionOptions {
    public videoQuality?: number;
    public qualityIndex?: number;
    constructor(args?: ISubscriptionOptionsArgs) {
        if (args != null && args.videoQuality != null) {
            this.videoQuality = args.videoQuality;
        }
        if (args != null && args.qualityIndex != null) {
            this.qualityIndex = args.qualityIndex;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("SubscriptionOptions");
        if (this.videoQuality != null) {
            output.writeFieldBegin("videoQuality", thrift.Thrift.Type.I32, 1);
            output.writeI32(this.videoQuality);
            output.writeFieldEnd();
        }
        if (this.qualityIndex != null) {
            output.writeFieldBegin("qualityIndex", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.qualityIndex);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): SubscriptionOptions {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_1: number = input.readI32();
                        _args.videoQuality = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.qualityIndex = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new SubscriptionOptions(_args);
    }
}
