/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IUnsubscribeRequestArgs {
    topic?: string;
    version?: number;
    topicId?: number;
}
export class UnsubscribeRequest {
    public topic?: string;
    public version?: number;
    public topicId?: number;
    constructor(args?: IUnsubscribeRequestArgs) {
        if (args != null && args.topic != null) {
            this.topic = args.topic;
        }
        if (args != null && args.version != null) {
            this.version = args.version;
        }
        if (args != null && args.topicId != null) {
            this.topicId = args.topicId;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("UnsubscribeRequest");
        if (this.topic != null) {
            output.writeFieldBegin("topic", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.topic);
            output.writeFieldEnd();
        }
        if (this.version != null) {
            output.writeFieldBegin("version", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.version);
            output.writeFieldEnd();
        }
        if (this.topicId != null) {
            output.writeFieldBegin("topicId", thrift.Thrift.Type.I32, 3);
            output.writeI32(this.topicId);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): UnsubscribeRequest {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.topic = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.version = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_3: number = input.readI32();
                        _args.topicId = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new UnsubscribeRequest(_args);
    }
}
