/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IWhiteboardOutputStateArgs {
    excalidraw_url?: string;
    excalidraw_generated_by?: string;
}
export class WhiteboardOutputState {
    public excalidraw_url?: string;
    public excalidraw_generated_by?: string;
    constructor(args?: IWhiteboardOutputStateArgs) {
        if (args != null && args.excalidraw_url != null) {
            this.excalidraw_url = args.excalidraw_url;
        }
        if (args != null && args.excalidraw_generated_by != null) {
            this.excalidraw_generated_by = args.excalidraw_generated_by;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("WhiteboardOutputState");
        if (this.excalidraw_url != null) {
            output.writeFieldBegin("excalidraw_url", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.excalidraw_url);
            output.writeFieldEnd();
        }
        if (this.excalidraw_generated_by != null) {
            output.writeFieldBegin("excalidraw_generated_by", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.excalidraw_generated_by);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): WhiteboardOutputState {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.excalidraw_url = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.excalidraw_generated_by = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new WhiteboardOutputState(_args);
    }
}
