/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IWorkroomsAssetArgs {
    asset_name?: string;
    encrypted_asset_id?: string;
    asset_url?: string;
}
export class WorkroomsAsset {
    public asset_name?: string;
    public encrypted_asset_id?: string;
    public asset_url?: string;
    constructor(args?: IWorkroomsAssetArgs) {
        if (args != null && args.asset_name != null) {
            this.asset_name = args.asset_name;
        }
        if (args != null && args.encrypted_asset_id != null) {
            this.encrypted_asset_id = args.encrypted_asset_id;
        }
        if (args != null && args.asset_url != null) {
            this.asset_url = args.asset_url;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("WorkroomsAsset");
        if (this.asset_name != null) {
            output.writeFieldBegin("asset_name", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.asset_name);
            output.writeFieldEnd();
        }
        if (this.encrypted_asset_id != null) {
            output.writeFieldBegin("encrypted_asset_id", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.encrypted_asset_id);
            output.writeFieldEnd();
        }
        if (this.asset_url != null) {
            output.writeFieldBegin("asset_url", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.asset_url);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): WorkroomsAsset {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.asset_name = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.encrypted_asset_id = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.asset_url = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new WorkroomsAsset(_args);
    }
}
