/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IWorkroomInputStateArgs {
    type?: number;
    conversation_id?: string;
    participant_ids?: Array<string>;
}
export class WorkroomInputState {
    public type?: number;
    public conversation_id?: string;
    public participant_ids?: Array<string>;
    constructor(args?: IWorkroomInputStateArgs) {
        if (args != null && args.type != null) {
            this.type = args.type;
        }
        if (args != null && args.conversation_id != null) {
            this.conversation_id = args.conversation_id;
        }
        if (args != null && args.participant_ids != null) {
            this.participant_ids = args.participant_ids;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("WorkroomInputState");
        if (this.type != null) {
            output.writeFieldBegin("type", thrift.Thrift.Type.I32, 1);
            output.writeI32(this.type);
            output.writeFieldEnd();
        }
        if (this.conversation_id != null) {
            output.writeFieldBegin("conversation_id", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.conversation_id);
            output.writeFieldEnd();
        }
        if (this.participant_ids != null) {
            output.writeFieldBegin("participant_ids", thrift.Thrift.Type.LIST, 3);
            output.writeListBegin(thrift.Thrift.Type.STRING, this.participant_ids.length);
            this.participant_ids.forEach((value_1: string): void => {
                output.writeString(value_1);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): WorkroomInputState {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.type = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.conversation_id = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_4: Array<string> = new Array<string>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_5: string = input.readString();
                            value_4.push(value_5);
                        }
                        input.readListEnd();
                        _args.participant_ids = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new WorkroomInputState(_args);
    }
}
