/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as VRParticipant from "./VRParticipant";
export interface IWorkroomsVROutputStateArgs {
    participants?: Map<string, VRParticipant.VRParticipant>;
}
export class WorkroomsVROutputState {
    public participants?: Map<string, VRParticipant.VRParticipant>;
    constructor(args?: IWorkroomsVROutputStateArgs) {
        if (args != null && args.participants != null) {
            this.participants = args.participants;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("WorkroomsVROutputState");
        if (this.participants != null) {
            output.writeFieldBegin("participants", thrift.Thrift.Type.MAP, 1);
            output.writeMapBegin(thrift.Thrift.Type.STRING, thrift.Thrift.Type.STRUCT, this.participants.size);
            this.participants.forEach((value_1: VRParticipant.VRParticipant, key_1: string): void => {
                output.writeString(key_1);
                value_1.write(output);
            });
            output.writeMapEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): WorkroomsVROutputState {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.MAP) {
                        const value_2: Map<string, VRParticipant.VRParticipant> = new Map<string, VRParticipant.VRParticipant>();
                        const metadata_1: thrift.TMap = input.readMapBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const key_2: string = input.readString();
                            const value_3: VRParticipant.VRParticipant = VRParticipant.VRParticipant.read(input);
                            value_2.set(key_2, value_3);
                        }
                        input.readMapEnd();
                        _args.participants = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new WorkroomsVROutputState(_args);
    }
}
